name: Node.js CI

on:
  push:
    branches: [ "master" ] 

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "**/package-lock.json"
    - name: install nm
      run: npm ci
    - name: start
      run: sudo pm2 kill
    - name: start2
      run: npm start
      env:
        CI: false
        GENERATE_SOURCEMAP: false
        URI: '${{ secrets.URI }}'
        USEREMAIL: '${{ secrets.USEREMAIL }}'
        USERPASSWORD: '${{ secrets.USERPASSWORD }}'
        RAZORPAY_KEY_ID: '${{ secrets.RAZORPAY_KEY_ID }}'
        RAZORPAY_SECRET: '${{ secrets.RAZORPAY_SECRET }}'
